# Generated by Django 5.1.3 on 2024-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
