# Generated by Django 5.1.3 on 2024-11-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_feature_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorys',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='features',
        ),
    ]
