# Generated by Django 5.1.3 on 2024-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_remove_product_features_feature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_name',
            field=models.ImageField(upload_to='static/uploads/slider_imgs/'),
        ),
    ]
