# Generated by Django 5.1.3 on 2024-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productimage_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_name',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='static/uploads/slider_imgs/'),
            preserve_default=False,
        ),
    ]
