# Generated by Django 5.1.3 on 2024-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_brand_is_delete_remove_category_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='static/uploads/product_imgs/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/uploads/product_imgs/'),
        ),
    ]
