# Generated by Django 5.1.3 on 2024-11-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_useraddress_city_alter_useraddress_state_and_more'),
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.state')),
            ],
        ),
    ]
