# Generated by Django 5.1.3 on 2024-11-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=1, upload_to='static/uploads/slider_imgs/'),
            preserve_default=False,
        ),
    ]
